[[pages]]
path = "intro.py"
name = "Introduction"
icon = "🏠"

[[pages]]
path = "pages/0_tools.py"
name = "Must-know"
icon = "🛠"

[[pages]]
path = "pages/1_ols.py"
name = "Linear Regression"
icon = "📈"

[[pages]]
path = "pages/2_ols_3d.py"
name = "OLS in 3D"
icon = "🔍"

[[pages]]
path = "pages/3_fit.py"
name = "Fit Measures"
icon = "🎯"