[[pages]]
path = "intro.py"
name = "Introduction"
icon = "🏠"

[[pages]]
path = "pages/0_tools.py"
name = "Tools for Econometrics"
icon = "🛠"

[[pages]]
path = "pages/1_ols.py"
name = "Linear Regression"
icon = "📈"

[[pages]]
path = "pages/2_fit.py"
name = "Fit Measures"
icon = "🎯"